version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SPRING_PROFILE=production
      - POSTGRESQL_URL="postgresql_url"
      - POSTGRESQL_USERNAME="postgresql_username"
      - POSTGRESQL_PASSWORD="postgresql_password"
      - POSTGRESQL_DIALECT="postgresql_dialect"
      - KEYCLOAK_JWT_ISSUER_URI="keycloak_jwt_issuer_uri"
      - KEYCLOAK_JWT_JWK_SET_URI="keycloak_jwt_jwk_set_uri"
      - DDL_AUTO="create"

